Repository dev-mingle/dev-mingle-server, pull requests merged in 2023-09, with the labels that each got.

#1 BugFix: flyway 최초 마이그레이션 시 참조키 생성 에러 수정
  src/main/resources/db/migration/V1__init_db.sql
Labels: bug

#4 BugFix: Securiy Config 에서 루트 경로 접근 시 401 에러가 발생하는 현상 수정
  src/main/java/com/example/dm/security/SecurityConfig.java
Labels: bug

#7 Add : application level configuration
  src/main/java/com/example/dm/ApplicationConfig.java
  src/main/java/com/example/dm/DevMingleApplication.java
Labels: feature

#25 Add: 팔로우 등록 API 개발
  src/main/java/com/example/dm/controller/BaseController.java
  src/main/java/com/example/dm/controller/FollowController.java
  src/main/java/com/example/dm/dto/follows/FollowAddDto.java
  src/main/java/com/example/dm/dto/follows/FollowInfoDto.java
  src/main/java/com/example/dm/dto/follows/TargetUserInfoDto.java
  src/main/java/com/example/dm/entity/Follows.java
  src/main/java/com/example/dm/entity/Images.java
  src/main/java/com/example/dm/entity/UserProfiles.java
  src/main/java/com/example/dm/exception/ApiResultStatus.java
  src/main/java/com/example/dm/exception/FollowException.java
  src/main/java/com/example/dm/repository/FollowRepository.java
  src/main/java/com/example/dm/repository/UserProfileRepository.java
  src/main/java/com/example/dm/service/FollowService.java
Labels: feature

#29 Add: 팔로우 취소 API 개발
  src/main/java/com/example/dm/controller/FollowController.java
  src/main/java/com/example/dm/exception/ApiResultStatus.java
  src/main/java/com/example/dm/repository/FollowRepository.java
  src/main/java/com/example/dm/service/FollowService.java
Labels: feature

#31 Add: PostGIS 관련 설정 추가
  build.gradle
  docker-compose.local.yml
  src/main/resources/db/migration/V3__alter_column_posts.sql
Labels: feature

#32 Create: 회원가입 및 이메일 인증 및 일부 수정
  build.gradle
  src/main/java/com/example/dm/controller/AuthController.java
  src/main/java/com/example/dm/dto/form/SignupForm.java
  src/main/java/com/example/dm/dto/form/SignupUserData.java
  src/main/java/com/example/dm/dto/form/SignupUserProfilesData.java
  src/main/java/com/example/dm/entity/DeletedEntity.java
  src/main/java/com/example/dm/entity/UserProfiles.java
  src/main/java/com/example/dm/entity/Users.java
  src/main/java/com/example/dm/repository/UserProfilesRepository.java
  src/main/java/com/example/dm/repository/UsersRepository.java
Labels: feature

#34 Update: #33 충돌파일 다시 수정 업데이트
  src/main/java/com/example/dm/config/SecurityConfig.java
  src/main/java/com/example/dm/exception/ApiResultStatus.java
  src/main/resources/application.yml
Labels: feature

#38 Redis 연동 작업
  build.gradle
  docker-compose.local.yml
  docker-compose.yml
  src/main/java/com/example/dm/config/ApplicationConfig.java
  src/main/java/com/example/dm/config/RedisCacheConfig.java
  src/main/java/com/example/dm/dto/follows/FollowInfoDto.java
  src/main/java/com/example/dm/entity/BaseTimeEntity.java
  src/main/java/com/example/dm/entity/DeletedEntity.java
  src/main/java/com/example/dm/service/FollowService.java
  src/main/java/com/example/dm/service/S3Service.java
  src/main/java/com/example/dm/util/RedisUtil.java
  src/main/resources/application-datasource.yml
  src/main/resources/application.yml
Labels: feature

#43 Update: 삭제된 유저 고려한 이메일/닉네임 중복 체크 적용
  src/main/java/com/example/dm/controller/AuthController.java
  src/main/java/com/example/dm/controller/UserController.java
  src/main/java/com/example/dm/entity/Users.java
  src/main/java/com/example/dm/exception/ApiResultStatus.java
  src/main/java/com/example/dm/repository/UserProfileRepository.java
  src/main/java/com/example/dm/repository/UserProfilesRepository.java
  src/main/java/com/example/dm/repository/UsersRepository.java
  src/main/java/com/example/dm/service/AuthService.java
Labels: enhancement

#46 Fix: TokenFilter에서 doFilter 로직 변경
  src/main/java/com/example/dm/security/jwt/TokenFilter.java
Labels: bug

#47 Update: AntPathRequestMatcher로 변경
  src/main/java/com/example/dm/security/jwt/TokenFilter.java
Labels: enhancement

#48 Update: Security context 닉네임 담기
  src/main/java/com/example/dm/config/SecurityConfig.java
  src/main/java/com/example/dm/controller/AuthController.java
  src/main/java/com/example/dm/controller/UserController.java
  src/main/java/com/example/dm/dto/users/ChangePwdDto.java
  src/main/java/com/example/dm/dto/users/LoginDto.java
  src/main/java/com/example/dm/dto/users/MypageDto.java
  src/main/java/com/example/dm/dto/users/SignupDto.java
  src/main/java/com/example/dm/dto/users/SignupUserProfilesResponse.java
  src/main/java/com/example/dm/dto/users/SignupUserResponse.java
  src/main/java/com/example/dm/dto/users/UserProfileResponse.java
  src/main/java/com/example/dm/entity/LoginUser.java
  src/main/java/com/example/dm/entity/UserProfiles.java
  src/main/java/com/example/dm/entity/Users.java
  src/main/java/com/example/dm/exception/ApiResultStatus.java
  src/main/java/com/example/dm/repository/UsersRepository.java
  src/main/java/com/example/dm/security/jwt/TokenFilter.java
  src/main/java/com/example/dm/security/jwt/TokenProvider.java
  src/main/java/com/example/dm/service/AuthService.java
  src/main/java/com/example/dm/service/UserService.java
  src/main/java/com/example/dm/util/MailSender.java
  src/main/java/com/example/dm/util/PasswordGenerator.java
  src/main/resources/application-auth.yml
Labels: enhancement

#51 Add: build test 추가
  .github/workflows/UnitTest.yml
  README.md
  build.gradle
  src/test/java/com/example/dm/DevMingleApplicationTest.java
  src/test/resources/application.yml
  start-server.sh
Labels: feature
